### ISSUE TITLE
Permutations exercise missing for Lab2

### ISSUE THREAD

**Issue by SimonBaars** [Descalon/SSVT#4]
Hey all,

I noticed that the permutations exercise is missing from your deliverable of Lab 2. Or am I looking in the wrong place? If so, please point me to it.

Please note that if you indeed forgot it and no member of the group has completed this exercise, it is now too late to add it as the deadline has passed.

**Comment by Descalon** [comment]
Ah yes. We seem to have forgotten to add that one for the final deliverable.. You can find a suitable work out of the exercise in https://github.com/Descalon/SSVT/blob/213d853abe0458ecf320ca9c01ee6b2247f08a2e/Lab2/yoni/week2.hs#L92

**Comment by SimonBaars** [comment]
Okay, we will grade this exercise for this time. Please be more careful next time, as we will not allow the same opportunity.
